version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "installing"
      - npm install
  pre_build:
    commands:
      - echo "Check Version"
      - npm --version
      - node --version
      - git --version
      - git status
      - ls
      - echo "Check Lint"
      - npm run lint
      - echo "Run Test Coverage"
      - npm run testc
      - echo "Sonar Scanner"
      - npm run sonar:scan
      - echo "Sonar Gateway"
      - npm run sonar:gateway
      - echo "Install Heroku"
      - npm i -g heroku
      - heroku --version
      - echo "Init git"
      - git init
      - git add .
      - git commit -m "Push to heroku"
      - echo "Push to Heroku"
      - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
